### ISSUE TITLE
新版本预约失败

### ISSUE THREAD

**Issue by vegetabled0g** [LinChiQ/Kust-GoToLib#2]
这个公众号更新之后老哥有没有遇到，返回信息是reserve true 但是并没有抢到座位的情况啊

**Comment by lsjhaha** [comment]
我也遇到了这种情况，请问你解决了吗

**Comment by LinChiQ** [comment]
在reserve为true后，另有一个api是可以判断现在是否选上座位的，再后面加上这个api判断，没选上就接着选，一般选到第二次才成功选上
